"""Generate iscas_values.tex: control-chain constants and the residual-detectability bound.

Input: data/spin1_equivalence.json (output of analysis/project1/spin1_equivalence.py).
Constants match the long paper (gamma, D, B0 = 10 mT, 20 settings of 1000 shots).
Detectability: the most favorable test for the defender knows the per-setting residual
delta exactly (a matched filter). With n settings its statistic has mean delta*sqrt(n)/sigma,
so 50% power at one-sided level alpha needs n >= (z_{1-alpha} * sigma / delta)^2.
Any real detector needs at least this many settings.
"""

import json
import math
from pathlib import Path
from statistics import NormalDist

HERE = Path(__file__).resolve().parent.parent
spin = json.loads((HERE / "data/spin1_equivalence.json").read_text())

GAMMA_HZ = 28.025e9  # Hz/T
D_HZ = 2.870e9
B0 = 10e-3
SPOOF = 100e-9
SETTINGS_PER_SEQ = 20
ALPHA = 0.01

upper_line = D_HZ + GAMMA_HZ * B0  # m_s = 0 -> +1 transition addressed at B0
offset_hz = GAMMA_HZ * SPOOF
single_bias_nT = 1e-6 * (D_HZ / GAMMA_HZ + B0) * 1e9  # 1 ppm clock error, single transition
dual_bias_nT = 1e-6 * B0 * 1e9  # 1 ppm clock error, dual transition

z = NormalDist().inv_cdf(1 - ALPHA)
sigma = spin["shot_noise_1000"]
by_bias = {round(r["bias_field_tesla"] * 1e3): r["max_population_difference"] for r in spin["summary"]}


def settings_needed(delta):
    return math.ceil((z * sigma / delta) ** 2)


def thousands(n):
    return f"{n:,}".replace(",", "{,}")


worst = settings_needed(spin["max_population_difference"])
nominal = settings_needed(by_bias[10])
values = {
    "UpperLineGHz": f"{upper_line / 1e9:.2f}",
    "SpoofOffsetkHz": f"{offset_hz / 1e3:.1f}",
    "SpoofOffsetPpm": f"{offset_hz / upper_line * 1e6:.2f}",
    "ClockSingleBias": f"{single_bias_nT:.0f}",
    "ClockDualBias": f"{dual_bias_nT:.0f}",
    "SpinNominalDiff": f"{by_bias[10] * 1e4:.1f}",
    "DetectSettingsWorst": thousands(worst),
    "DetectSequencesWorst": thousands(math.ceil(worst / SETTINGS_PER_SEQ)),
    "DetectSettingsNominal": thousands(nominal),
    "DetectSequencesNominal": thousands(math.ceil(nominal / SETTINGS_PER_SEQ)),
}

assert abs(offset_hz - 2802.5) < 1 and round(single_bias_nT) == 112  # consistent with long paper

lines = ["% Generated by scripts/iscas_values.py; do not edit numbers by hand."]
lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in values.items()]
(HERE / "iscas_values.tex").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
